### ISSUE TITLE
Twitch partnership validation fails

### ISSUE THREAD

**Issue by CynicalMedia** [DorCoMaNdO/ModBot#20]
I have tried multiple times to get my modbot to work. I keep getting an error where it says failed to validate channels partnership status. What does this mean? why cant I use my modbot if I dont have a partnership with twitch. Can someone explain why it's doing this. Thank you.

**Comment by yoBigD** [comment]
I started having the same issue since yesterday @CynicalMedia

**Comment by thavillain91** [comment]
i have been running into the same problem for a couple of days now. Modbot is important to me and my channel and the only real alternative cost 10$ a month. i have  searched for a fix to this problem and it seems like there is none. in the about tab i can see there is one person live that is connected to Modbot and he is using version 1.9 the a version of Modbot i can find anywhere. any knowledge as to what the hell is going on would be appreciated

**Comment by DorCoMaNdO** [comment]
Please read the post I just submitted about the issue over on the ModBot website [here](https://modbot.wordpress.com/2016/09/16/twitch-partnership-validation-issuesrecoding-modbot/).
