### ISSUE TITLE
Current modbot issue.

### ISSUE THREAD

**Issue by CynicalMedia** [DorCoMaNdO/ModBot#21]
After trying to reset my modbot so I could reactivate it. Everytime I try to get my access tokens but this keeps happening
https://gyazo.com/ff50571bf2507e932772d09f8d286b41
The access token just randomly disappears. So I cant even reenable my modbot because I cant get anything working with it. I use google chrome and I'm beyond confused right now. Is there a fix for it?

**Comment by DorCoMaNdO** [comment]
I don't really know the cause for it but I do know that a different browser usually works, you could also try incognito.

**Comment by CynicalMedia** [comment]
I'ved tried firefox chrome and internet explorer and for some reason none of them are working. Any work arounds?

**Comment by DorCoMaNdO** [comment]
I'll create a landing page rather than redirect you to Twitch sometime in the next few days hopefully.

For the time being, since you were able to capture the token in the recording, you could try doing so again and manually entering the token yourself.

**Comment by CynicalMedia** [comment]
I'll see what I can do. If you dont mind me asking when do you think it'll be updated if you do, do it?

**Comment by DorCoMaNdO** [comment]
This should now be fixed, both the links in the troubleshooting section and the bot's automatic process have been updated, both should be more reliable.
