### ISSUE TITLE
!giveaway not working

### ISSUE THREAD

**Issue by JonathanDCohen** [DorCoMaNdO/ModBot#6]
I installed teh giveaway extension but the bot doesn't respond to the either the !giveaway or !raffle commands.  I spent $40 on giveaway just sitting in my steam account.

**Comment by DorCoMaNdO** [comment]
Check the console for loading errors for the extension, if there are any, email me the error log from the Logs sub-folder in the Data folder to CoMaNdO.ModBot@gmail.com, in the content of the message link to this issue.
